continual:
  outputs:
    dev:
      account: wr40705.us-east-1
      client_session_keep_alive: false
      database: predictive_maintenance_bm
      password: k4!!3xG9hMS8
      query_tag: pred_main
      role: continual_public
      schema: azure_vm
      threads: 4
      type: snowflake
      user: brendan
      warehouse: COMPUTE_WH
  target: dev
dbt_demand_forecasting:
  outputs:
    dev:
      account: wr40705.us-east-1
      database: brendan_test
      password: k4!!3xG9hMS8
      role: CONTINUAL_PUBLIC
      schema: DEMAND_FORECASTING_MEAL_DELIVERY
      threads: 1
      type: snowflake
      user: brendan
      warehouse: compute_wh
  target: dev
jaffle_shop:
  outputs:
    dev:
      dataset: dbt_brendan
      fixed_retries: 1
      keyfile: /Users/bm/.dbt/bm-dbt-user.json
      location: US
      method: service-account
      priority: interactive
      project: continual-dev
      threads: 1
      timeout_seconds: 300
      type: bigquery
  target: dev
ml_delivery:
  outputs:
    dev:
      catalog: hive_metastore
      host: dbc-a85f130d-1242.cloud.databricks.com
      http_path: sql/protocolv1/o/2526374738320965/1103-144613-5vj607xk
      schema: default
      threads: 1
      token: dapifd2a58c773c0b40cfe5bce835f66ec08
      type: databricks
  target: dev
mrr:
  outputs:
    dev:
      account: wr40705.us-east-1
      database: BRENDAN_TEST
      password: k4!!3xG9hMS8
      role: CONTINUAL_PUBLIC
      schema: PUBLIC
      threads: 4
      type: snowflake
      user: brendan
      warehouse: compute_wh
  target: dev
playbook:
  outputs:
    dev:
      account: wr40705.us-east-1
      client_session_keep_alive: false
      database: BRENDAN_TEST
      password: k4!!3xG9hMS8
      query_tag: dbt_example
      role: CONTINUAL_PUBLIC
      schema: dbt_example
      threads: 4
      type: snowflake
      user: brendan
      warehouse: compute_wh
  target: dev
